version: "3"

services:
  intellij:
    build: .
    image: lumunix/intellij-idea-docker
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - ./intellij-idea-data:/home/developer/.IdeaIC2021.1
      - ./IdeaProjects:/home/developer/IdeaProjects
      - /tmp/.X11-unix:/tmp/.X11-unix

volumes:
  intellij-idea-data:
  IdeaProjects:
